[project]
name = "vlm-ocr"
version = "0.1.0"
description = "VLM OCR project"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "notebook>=7.4.4",
    "ipykernel>=6.30.1",
]

[tool.uv]
dev-dependencies = []